version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: vacancies
    volumes:
          - ./pgdata:/var/lib/postgresql/data
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend/
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:12345@db:5432/vacancies
      DATABASE_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./frontend:/app/frontend

  frontend:
    build: ./frontend/
    ports:
      - "80:80"
